### ISSUE TITLE
PSR-4 non-compliance warning by composer

### ISSUE THREAD

**Issue by abishekrsrikaanth** [ipinfo/php#12] opened 2020-03-13 20:43 UTC
Here is the error I get every time I run composer update.

```
Deprecation Notice: Class ipinfo\ipinfo\cache\CacheInterface located in ./vendor/ipinfo/ipinfo/src/cache/Interface.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:185
Deprecation Notice: Class ipinfo\ipinfo\cache\DefaultCache located in ./vendor/ipinfo/ipinfo/src/cache/Default.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:185
```

**Comment by peter279k** [comment] 2020-03-14 04:42
It seems that the ``PSR-4` autoloading will not be compatible on ``composer-2.0` version.

And I think it  should be fixed.

**Comment by peter279k** [comment] 2020-03-14 19:12
@abishekrsrikaanth, could you have the approaches about reproducing issue?

I cannot reproduce this issue by myself.

I try to use following issue to reproduce:

- Using the composer-1.10.1` to install `ipinfo/ipinfo` package.
```
php ~/composer.phar require ipinfo/ipinfo
```
- Then changing the `ipinfo/ipinfo` version `^1.1` to `dev-master` on `composer.json` file.
- Using the `php ~/composer.phar require ipinfo/ipinfo` to update the `ipinfo/ipinfo` package.

And I don't have any message about deprecation notice message.

**Comment by abishekrsrikaanth** [comment] 2020-03-16 13:20
I have this package installed on an existing project. I get this error message every time I run `composer update` or running `composer update "ipinfo/ipinfo". Both these should output the above deprecation warning messages on your console.

**Comment by peter279k** [comment] 2020-03-16 18:24
Hi @abishekrsrikaanth, thanks for your approach and I can reproduce the issue as well.

You're right. It should release a major version to accomplish this issue :).

**Comment by umairkhan-dev** [comment] 2020-11-10 06:44
@peter279k 
Any update on PSR-4 compliance issue.

_composer.json_
```
{
    "config": {
        "optimize-autoloader": true,
        "sort-packages": true
    },
    "require": {
        "ipinfo/ipinfo": "dev-master"
    }
}
```
This seem to resolve the PSR-4 compliance issue with **composer 2.0.2** as composer cloned bde9ce0 commit by @coderholic.
However wouldn't it be better to push your latest changes to [packagist](https://packagist.org/packages/ipinfo/ipinfo) with newer version.

**Comment by UmanShahzad** [comment] 2020-11-12 10:46
We'll be releasing the latest version (actually, probably a 2.0.0 with some more fixes and updates) to packagist soon.

**Comment by UmanShahzad** [comment] 2020-11-20 09:15
https://packagist.org/packages/ipinfo/ipinfo#v2.0.0

**Closed by UmanShahzad** 2020-11-20 09:15 UTC

**Comment by bkmorse** [comment] 2021-02-22 21:37
run command: 

composer self-update 1.6.3 

to downgrade to an earlier version of composer, temporary fix.
